name: Enforce English for issues
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const CJK = /[\p{Script=Han}\u3000-\u303F\uFF00-\uFFEF]/u;

            const issue = context.payload.issue || {};
            const title = issue.title || "";
            const body  = (issue.body || "").trim();

            const text = `${title}\n${body}`;
            const hasCJK = CJK.test(text);

            core.info(`en-only-issues: titleLen=${title.length}, bodyLen=${body.length}, hasCJK=${hasCJK}`);
            core.info(`en-only-issues: title="${title.replace(/\n/g,' ')}"`);
            core.info(`en-only-issues: bodyPreview="${body.slice(0,80).replace(/\n/g,' ')}${body.length>80?'…':''}"`);

            if (!hasCJK) {
              core.info('No CJK detected. Skipping.');
              return;
            }

            const { owner, repo } = context.repo;
            const number = issue.number;

            async function ensureLabel(name, color, description) {
              try {
                await github.rest.issues.getLabel({ owner, repo, name });
                core.info(`Label "${name}" exists.`);
              } catch {
                core.info(`Label "${name}" not found. Creating...`);
                try {
                  await github.rest.issues.createLabel({ owner, repo, name, color, description });
                  core.info(`Label "${name}" created.`);
                } catch (e) {
                  core.warning(`Create label failed (may exist): ${e.message}`);
                }
              }
            }
            await ensureLabel('non-english', 'B60205', 'Contains non-English text');

            try {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: number, labels: ['non-english']
              });
              core.info('Label applied.');
            } catch (e) {
              core.warning(`Add label failed: ${e.message}`);
            }

            try {
              await github.rest.issues.createComment({
                owner, repo, issue_number: number,
                body: 'English only please.'
              });
              core.info('Comment posted.');
            } catch (e) {
              core.warning(`Comment failed: ${e.message}`);
            }

            try {
              await github.rest.issues.update({
                owner, repo, issue_number: number, state: 'closed'
              });
              core.info('Issue closed.');
            } catch (e) {
              core.warning(`Close failed: ${e.message}`);
            }

            try {
              await github.rest.issues.lock({
                owner, repo, issue_number: number, lock_reason: 'off-topic'
              });
              core.info('Issue locked.');
            } catch (e) {
              core.warning(`Lock failed: ${e.message}`);
            }
